[package]
name = "mayaqua"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib", "cdylib"]

[[bin]]
name = "header-prune"
path = "utility/header-prune/main.rs"

[dependencies]
antlr4rust = "0.5.2"
cbindgen = "0.29.2"
openssl = "0.10.75"
socket2 = "0.6.2"
tokio = "1.49.0"
