[package]
name = "mayaqua"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib", "cdylib"]

[[bin]]
name = "header-prune"
path = "utility/main.rs"

[dependencies]
antlr4rust = "0.5.2"
cbindgen = "0.29.2"
